# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

version: 0.2

phases:

    post_build:
        commands:
            - aws lambda get-function --function-name $LAMBDA_NAME:$LAMBDA_ALIAS --query 'Code.Location' | xargs wget -O lambda.zip
            - aws s3 cp lambda.zip s3://$S3_BUCKET/lambda.zip
            - BOT_VERSION=$(aws lex-models get-bot-alias --name $BOT_ALIAS --bot-name $BOT_NAME | sed -n '/ *"botVersion". *"/ { s///; s/".*//; p; }')
            - aws lex-models get-export --name $BOT_NAME --resource-type BOT --resource-version $BOT_VERSION --export-type LEX | sed -n '/ *"url". *"/ { s///; s/".*//; p; }' | xargs wget -O lex.zip
            - aws s3 cp lex.zip s3://$S3_BUCKET/lex.zip
